# Generated by Django 3.2 on 2022-12-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='desciption',
            new_name='description',
        ),
    ]
