# Generated by Django 3.2.16 on 2023-01-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_review_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='platfrom',
            new_name='platform',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
